import type { ThemeConfig, ThemePresetId } from "@/types/theme";

export const FONT_OPTIONS = [
  "Cormorant Garamond",
  "Playfair Display",
  "Libre Baskerville",
  "Newsreader",
  "Inter",
  "Source Sans 3",
  "Lora",
  "DM Sans",
  "Outfit",
  "Manrope",
  "Fraunces",
  "IBM Plex Sans",
];

const base = (partial: ThemeConfig): ThemeConfig => partial;

export const THEME_PRESETS: Record<ThemePresetId, ThemeConfig> = {
  wedding: base({
    presetId: "wedding",
    presetName: "Elegant Rose",
    colors: {
      primary: "#5c3d4a",
      secondary: "#c9a07a",
      accent: "#b76e79",
      background: "#f7f1ea",
      text: "#2c211c",
      muted: "#7a6a62",
      button: "#5c3d4a",
      buttonText: "#fbf7f2",
      card: "#fffaf6",
      border: "#e6d8cc",
    },
    typography: {
      headingFont: "Cormorant Garamond",
      bodyFont: "Source Sans 3",
      baseSize: 16,
      headingWeight: 500,
      bodyWeight: 400,
    },
    layout: "card",
    background: { type: "gradient", value: "#f7f1ea", secondary: "#efe2d6" },
    decorations: { ornaments: true, animation: "subtle" },
    cardStyle: { radius: 18, shadow: "soft", border: true },
    buttonStyle: { radius: 999, shadow: false },
  }),
  christmas: base({
    presetId: "christmas",
    presetName: "Winter Celebration",
    colors: {
      primary: "#1f3d2b",
      secondary: "#8b1e2d",
      accent: "#c4a35a",
      background: "#f4efe6",
      text: "#1b241d",
      muted: "#5d685f",
      button: "#8b1e2d",
      buttonText: "#f8f3ea",
      card: "#fffaf2",
      border: "#ddd2c0",
    },
    typography: {
      headingFont: "Playfair Display",
      bodyFont: "Source Sans 3",
      baseSize: 16,
      headingWeight: 600,
      bodyWeight: 400,
    },
    layout: "centered",
    background: { type: "gradient", value: "#f4efe6", secondary: "#e7efe8" },
    decorations: { ornaments: true, animation: "festive" },
    cardStyle: { radius: 16, shadow: "lifted", border: true },
    buttonStyle: { radius: 8, shadow: true },
  }),
  halloween: base({
    presetId: "halloween",
    presetName: "Midnight Halloween",
    colors: {
      primary: "#f27a21",
      secondary: "#7b4ea3",
      accent: "#f2c14e",
      background: "#14110f",
      text: "#f4ece3",
      muted: "#b8aaa0",
      button: "#f27a21",
      buttonText: "#1a120c",
      card: "#1d1916",
      border: "#3a322c",
    },
    typography: {
      headingFont: "Fraunces",
      bodyFont: "IBM Plex Sans",
      baseSize: 16,
      headingWeight: 600,
      bodyWeight: 400,
    },
    layout: "fullscreen",
    background: { type: "solid", value: "#14110f" },
    decorations: { ornaments: true, animation: "subtle" },
    cardStyle: { radius: 14, shadow: "none", border: true },
    buttonStyle: { radius: 6, shadow: false },
  }),
  birthday: base({
    presetId: "birthday",
    presetName: "Celebration",
    colors: {
      primary: "#2f5d8c",
      secondary: "#e07a5f",
      accent: "#81b29a",
      background: "#f6f4f0",
      text: "#1f2933",
      muted: "#667085",
      button: "#2f5d8c",
      buttonText: "#ffffff",
      card: "#ffffff",
      border: "#e4e0d8",
    },
    typography: {
      headingFont: "Fraunces",
      bodyFont: "Manrope",
      baseSize: 16,
      headingWeight: 600,
      bodyWeight: 400,
    },
    layout: "card",
    background: { type: "gradient", value: "#f6f4f0", secondary: "#eef3f8" },
    decorations: { ornaments: false, animation: "subtle" },
    cardStyle: { radius: 20, shadow: "soft", border: false },
    buttonStyle: { radius: 12, shadow: true },
  }),
  party: base({
    presetId: "party",
    presetName: "Electric Night",
    colors: {
      primary: "#111827",
      secondary: "#7c3aed",
      accent: "#22d3ee",
      background: "#0b1220",
      text: "#f8fafc",
      muted: "#94a3b8",
      button: "#7c3aed",
      buttonText: "#ffffff",
      card: "#111827",
      border: "#1f2937",
    },
    typography: {
      headingFont: "Outfit",
      bodyFont: "DM Sans",
      baseSize: 16,
      headingWeight: 600,
      bodyWeight: 400,
    },
    layout: "split",
    background: { type: "gradient", value: "#0b1220", secondary: "#1e1b4b" },
    decorations: { ornaments: false, animation: "subtle" },
    cardStyle: { radius: 16, shadow: "lifted", border: true },
    buttonStyle: { radius: 10, shadow: true },
  }),
  corporate: base({
    presetId: "corporate",
    presetName: "Boardroom",
    colors: {
      primary: "#16324f",
      secondary: "#4b5563",
      accent: "#0f766e",
      background: "#f4f6f8",
      text: "#111827",
      muted: "#6b7280",
      button: "#16324f",
      buttonText: "#ffffff",
      card: "#ffffff",
      border: "#e5e7eb",
    },
    typography: {
      headingFont: "IBM Plex Sans",
      bodyFont: "IBM Plex Sans",
      baseSize: 16,
      headingWeight: 600,
      bodyWeight: 400,
    },
    layout: "wide",
    background: { type: "solid", value: "#f4f6f8" },
    decorations: { ornaments: false, animation: "none" },
    cardStyle: { radius: 8, shadow: "none", border: true },
    buttonStyle: { radius: 4, shadow: false },
  }),
  baby_shower: base({
    presetId: "baby_shower",
    presetName: "Soft Linen",
    colors: {
      primary: "#6d7c6f",
      secondary: "#d8b4a0",
      accent: "#a8c5d4",
      background: "#f8f4ef",
      text: "#3f3a36",
      muted: "#7d746c",
      button: "#6d7c6f",
      buttonText: "#f8f4ef",
      card: "#fffcf8",
      border: "#eadfd4",
    },
    typography: {
      headingFont: "Newsreader",
      bodyFont: "Lora",
      baseSize: 16,
      headingWeight: 500,
      bodyWeight: 400,
    },
    layout: "card",
    background: { type: "gradient", value: "#f8f4ef", secondary: "#eef3f4" },
    decorations: { ornaments: true, animation: "subtle" },
    cardStyle: { radius: 22, shadow: "soft", border: true },
    buttonStyle: { radius: 999, shadow: false },
  }),
  graduation: base({
    presetId: "graduation",
    presetName: "Convocation",
    colors: {
      primary: "#1e3a5f",
      secondary: "#c5a46e",
      accent: "#9b1c31",
      background: "#f5f2ea",
      text: "#1a1f2b",
      muted: "#5c6475",
      button: "#1e3a5f",
      buttonText: "#f8f5ee",
      card: "#ffffff",
      border: "#ddd6c8",
    },
    typography: {
      headingFont: "Libre Baskerville",
      bodyFont: "Source Sans 3",
      baseSize: 16,
      headingWeight: 700,
      bodyWeight: 400,
    },
    layout: "centered",
    background: { type: "solid", value: "#f5f2ea" },
    decorations: { ornaments: false, animation: "none" },
    cardStyle: { radius: 12, shadow: "soft", border: true },
    buttonStyle: { radius: 6, shadow: false },
  }),
  anniversary: base({
    presetId: "anniversary",
    presetName: "Gilded Years",
    colors: {
      primary: "#3d2b1f",
      secondary: "#b08d57",
      accent: "#8c4a3a",
      background: "#f3ece2",
      text: "#2a211a",
      muted: "#6f6258",
      button: "#3d2b1f",
      buttonText: "#f7f0e6",
      card: "#fbf6ef",
      border: "#e2d4c2",
    },
    typography: {
      headingFont: "Cormorant Garamond",
      bodyFont: "Lora",
      baseSize: 16,
      headingWeight: 500,
      bodyWeight: 400,
    },
    layout: "split",
    background: { type: "gradient", value: "#f3ece2", secondary: "#e7dccb" },
    decorations: { ornaments: true, animation: "subtle" },
    cardStyle: { radius: 16, shadow: "soft", border: true },
    buttonStyle: { radius: 999, shadow: false },
  }),
  custom: base({
    presetId: "custom",
    presetName: "Custom",
    colors: {
      primary: "#1f2937",
      secondary: "#6b7280",
      accent: "#0f766e",
      background: "#f8f7f4",
      text: "#111827",
      muted: "#6b7280",
      button: "#111827",
      buttonText: "#ffffff",
      card: "#ffffff",
      border: "#e5e7eb",
    },
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      baseSize: 16,
      headingWeight: 600,
      bodyWeight: 400,
    },
    layout: "centered",
    background: { type: "solid", value: "#f8f7f4" },
    decorations: { ornaments: false, animation: "none" },
    cardStyle: { radius: 16, shadow: "soft", border: true },
    buttonStyle: { radius: 10, shadow: false },
  }),
};

export const THEME_GALLERY: ThemePresetId[] = [
  "wedding",
  "christmas",
  "halloween",
  "birthday",
  "party",
  "corporate",
  "baby_shower",
  "graduation",
  "anniversary",
  "custom",
];

export function cloneTheme(preset: ThemePresetId, overrides?: Partial<ThemeConfig>): ThemeConfig {
  const source = THEME_PRESETS[preset];
  return {
    ...source,
    ...overrides,
    colors: { ...source.colors, ...overrides?.colors },
    typography: { ...source.typography, ...overrides?.typography },
    background: { ...source.background, ...overrides?.background },
    decorations: { ...source.decorations, ...overrides?.decorations },
    cardStyle: { ...source.cardStyle, ...overrides?.cardStyle },
    buttonStyle: { ...source.buttonStyle, ...overrides?.buttonStyle },
    presetId: overrides?.presetId ?? preset,
  };
}
